language: node_js
node_js:
- '8'
sudo: false
cache:
  directories:
  - node_modules
install:
- yarn
script:
- yarn lint
- yarn build
deploy:
  provider: npm
  before_script: yarn version --new-version=$TRAVIS_TAG
  email: ertikass@gmail.com
  api_key:
    secure: s8wQAJYhAxc+8IQBVzuVL4rkr+RXKu98+JHZJoIcooRycbeKOunfhujTp1rYtikJU3lwIMYaHgLTHGPJx3eJcZVBdTU7RR98WMZ28TYvclsGOlUz5F9CzEoRky4WB7PPwl+RMykwEmwLQAUYYxXx4sHnoaPB/sdo5IXoQJCOcYv99PIB8o8w3RFyqULSk1mxmfqwAqvCFhMSKMQOoPybee+xPjJPkv0t6K5YAhyLeuir30tOptlSgt5evSjPpNrKxj3FSUMyBvqBqb3ezCCmk5uzqH8PUY9weEWqAI52tRMDHPb1wKZN2KgXd+Y+hdH41hSIj82qRJKr5CA68XJvingamrmGa3nmQS3AdoHIpXu+pk19orF4rJEIaXp594yA1cS7pOr5nGZzn9Le8514n6eNhDFKf6vIB3ZxFqPOYm8+kKZrgru8/eLLRMPYfW7c/kUuG4m515zqZLsM8SXj8l7ERzp9exwV0NKij8XZ63zdyWMJVF21h6eMcpwlyD+c8w0wxq7393o42OaF+CINfg8O3+l3HGjyfEkp9wnED6G3nROCRDGbmrMEh+/9WZJxn/b1JxqELYCXi4Agr9bgCgwqnr6oVrTmYUiaTmn8lOzdbL/enttv8JdL+03/CxZaWsOjWeTvtcAi5pqJgGcaWYn1p+6YhA4hXX2JyldaR4w=
  skip_cleanup: true
  on:
    tags: true
